### ISSUE TITLE
中文頁面出現了奇怪的亂碼

### ISSUE THREAD

**Issue by irvin** [twngo/privacytools-zh#1]
中文頁面最頂端出現了奇怪的亂碼，但是 index.html 中沒有
![2017-01-26 14 01 22](https://cloud.githubusercontent.com/assets/165936/22321455/f0b324c8-e3cf-11e6-9ddf-360a1b668d7a.png)

**Comment by jxtsai** [comment]
感謝告之，已經刪修了。
