### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by Lighsark** [twngo/privacytools-zh#18]
https://privacytools.twngo.xyz/providers/email/

> GPG 也無法方便地支援新的密碼學功能，如密鑰輪替（key rotation）和**隱密轉寄**（forward secrecy）。

forward secrecy 翻譯 隱密轉寄 不對吧？
[https://zh.wikipedia.org/zh-tw/%E5%89%8D%E5%90%91%E4%BF%9D%E5%AF%86](url)

**Comment by jxtsai** [comment]
感謝指正

待我晚點有空修改
